"""empty message

Revision ID: 250656cfacc9
Revises: 
Create Date: 2021-11-06 16:12:15.029850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '250656cfacc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=65), nullable=False),
    sa.Column('salt', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('login')
    )
    op.create_table('deck',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('thematic', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('deck_id', sa.INTEGER(), nullable=True),
    sa.Column('card_front', sa.String(length=200), nullable=True),
    sa.Column('card_back', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('nickname', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('second_name', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['login'], ['auth_user.login'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nickname')
    )
    op.create_table('user_card',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_nickname', sa.String(length=80), nullable=True),
    sa.Column('card_id', sa.INTEGER(), nullable=True),
    sa.Column('next_show_date', sa.DateTime(), nullable=False),
    sa.Column('algo_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_nickname'], ['user.nickname'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_deck',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_nickname', sa.String(length=80), nullable=True),
    sa.Column('deck_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_nickname'], ['user.nickname'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_deck')
    op.drop_table('user_card')
    op.drop_table('user')
    op.drop_table('card')
    op.drop_table('deck')
    op.drop_table('auth_user')
    # ### end Alembic commands ###
