"""empty message

Revision ID: f03b4c9273e6
Revises: 4e40f73baba1
Create Date: 2021-11-08 00:20:29.780277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f03b4c9273e6'
down_revision = '4e40f73baba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_card', sa.Column('deck_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'user_card', 'deck', ['deck_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_card', type_='foreignkey')
    op.drop_column('user_card', 'deck_id')
    # ### end Alembic commands ###
